#!/usr/bin/env bash
# Run on the TARGET machine. Driven by env vars from setup.sh:
#   PROFILE          one of profiles/*.env (without extension)
#   RTSP_PORT        default 8554
#   RTSP_PATH        default screen
#   SCREEN_CONNECTOR e.g. Virtual-1, HDMI-1
#   RTSP_USER        empty = no auth
#   RTSP_PASS
#   SUDO_PASSWORD    optional, used by `sudo -S` so install runs unattended
#   MEDIAMTX_VERSION default pinned below
set -euo pipefail

MEDIAMTX_VERSION="${MEDIAMTX_VERSION:-v1.18.2}"
RTSP_PORT="${RTSP_PORT:-8554}"
RTSP_PATH="${RTSP_PATH:-screen}"
SCREEN_CONNECTOR="${SCREEN_CONNECTOR:-Virtual-1}"
RTSP_USER="${RTSP_USER:-}"
RTSP_PASS="${RTSP_PASS:-}"
PROFILE="${PROFILE:?PROFILE env var is required}"

SRC_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
PROFILE_FILE="$SRC_DIR/profiles/${PROFILE}.env"
SERVICE_TMPL="$SRC_DIR/systemd/screen-to-rtsp.service.tmpl"
MEDIAMTX_UNIT="$SRC_DIR/systemd/mediamtx.service"
SCRIPT_FILE="$SRC_DIR/bin/screen-to-rtsp"

[[ -f $PROFILE_FILE ]] || { echo "Unknown profile: $PROFILE"; exit 1; }
[[ -f $SCRIPT_FILE  ]] || { echo "Missing $SCRIPT_FILE"; exit 1; }

run_sudo() {
  if [[ -n "${SUDO_PASSWORD:-}" ]]; then
    printf '%s\n' "$SUDO_PASSWORD" | sudo -S -p '' "$@"
  else
    sudo "$@"
  fi
}

step() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }

# ── 0. apt deps ──────────────────────────────────────────────────────────────
step "Installing apt packages"
DEBIAN_FRONTEND=noninteractive run_sudo apt-get update -qq
DEBIAN_FRONTEND=noninteractive run_sudo apt-get install -y -qq \
  python3-gi gir1.2-glib-2.0 \
  gstreamer1.0-tools gstreamer1.0-pipewire gstreamer1.0-plugins-base \
  gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
  gstreamer1.0-libav gstreamer1.0-rtsp \
  curl ca-certificates

# ── 1. MediaMTX binary ───────────────────────────────────────────────────────
step "Installing MediaMTX ${MEDIAMTX_VERSION}"
if ! command -v mediamtx >/dev/null 2>&1 || \
   [[ "$(mediamtx --version 2>/dev/null)" != "$MEDIAMTX_VERSION" ]]; then
  ARCH="$(uname -m)"
  case "$ARCH" in
    x86_64)  MARCH=amd64 ;;
    aarch64) MARCH=arm64v8 ;;
    armv7l)  MARCH=armv7 ;;
    *) echo "Unsupported arch: $ARCH"; exit 1 ;;
  esac
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT
  URL="https://github.com/bluenviron/mediamtx/releases/download/${MEDIAMTX_VERSION}/mediamtx_${MEDIAMTX_VERSION}_linux_${MARCH}.tar.gz"
  echo "  downloading $URL"
  curl -fsSL "$URL" -o "$TMP/m.tgz"
  tar xzf "$TMP/m.tgz" -C "$TMP"
  run_sudo install -m 0755 "$TMP/mediamtx" /usr/local/bin/mediamtx
fi
mediamtx --version

# ── 2. mediamtx.yml (with or without auth) ───────────────────────────────────
step "Writing /etc/mediamtx.yml"
YML="$(mktemp)"
{
  cat <<YAML
# Generated by ScreenToRtsp installer
logLevel: info
logDestinations: [stdout]
rtsp: yes
rtspAddress: :${RTSP_PORT}
rtspTransports: [tcp, udp]
rtmp: no
hls: no
webrtc: no
srt: no
api: no
metrics: no
playback: no
authMethod: internal
authInternalUsers:
YAML
  if [[ -n $RTSP_USER ]]; then
    cat <<YAML
  - user: ${RTSP_USER}
    pass: ${RTSP_PASS}
    ips: []
    permissions:
      - action: publish
      - action: read
      - action: playback
YAML
  else
    cat <<'YAML'
  - user: any
    pass:
    ips: []
    permissions:
      - action: publish
      - action: read
      - action: playback
YAML
  fi
  cat <<YAML
paths:
  ${RTSP_PATH}:
    source: publisher
YAML
} >"$YML"
run_sudo install -m 0640 "$YML" /etc/mediamtx.yml
rm -f "$YML"

# ── 3. mediamtx systemd unit ─────────────────────────────────────────────────
step "Installing mediamtx.service"
run_sudo install -m 0644 "$MEDIAMTX_UNIT" /etc/systemd/system/mediamtx.service
run_sudo systemctl daemon-reload
run_sudo systemctl enable --now mediamtx
run_sudo systemctl restart mediamtx

# ── 4. screen-to-rtsp script ─────────────────────────────────────────────────
step "Installing /usr/local/bin/screen-to-rtsp"
run_sudo install -m 0755 "$SCRIPT_FILE" /usr/local/bin/screen-to-rtsp

# ── 5. per-user config (profile + credentials) ───────────────────────────────
step "Writing user config (profile + credentials)"
CONF_DIR="$HOME/.config/screen-to-rtsp"
mkdir -p "$CONF_DIR"
{
  echo "# Generated by ScreenToRtsp installer — profile: $PROFILE"
  cat "$PROFILE_FILE"
  echo "SCREEN_CONNECTOR=${SCREEN_CONNECTOR}"
  echo "RTSP_URL=rtsp://localhost:${RTSP_PORT}/${RTSP_PATH}"
  echo "RTSP_LATENCY_MS=200"
} >"$CONF_DIR/profile.env"
chmod 0644 "$CONF_DIR/profile.env"

if [[ -n $RTSP_USER ]]; then
  cat >"$CONF_DIR/credentials.env" <<EOF
RTSP_USER=${RTSP_USER}
RTSP_PASS=${RTSP_PASS}
EOF
  chmod 0600 "$CONF_DIR/credentials.env"
else
  rm -f "$CONF_DIR/credentials.env"
fi

# ── 6. user systemd unit ─────────────────────────────────────────────────────
step "Installing screen-to-rtsp.service (user)"
mkdir -p "$HOME/.config/systemd/user"
install -m 0644 "$SERVICE_TMPL" "$HOME/.config/systemd/user/screen-to-rtsp.service"
systemctl --user daemon-reload
systemctl --user enable --now screen-to-rtsp.service
systemctl --user restart screen-to-rtsp.service

# ── 7. linger so it survives reboot without GUI login ────────────────────────
step "Enabling linger for $(whoami)"
run_sudo loginctl enable-linger "$(whoami)" || true

# ── 8. summary ───────────────────────────────────────────────────────────────
sleep 3
IP="$(hostname -I | awk '{print $1}')"
if [[ -n $RTSP_USER ]]; then
  URL_HUMAN="rtsp://${RTSP_USER}:<password>@${IP}:${RTSP_PORT}/${RTSP_PATH}"
else
  URL_HUMAN="rtsp://${IP}:${RTSP_PORT}/${RTSP_PATH}"
fi
cat <<EOF

╭─ Done ─────────────────────────────────────────────╮
  Profile:    ${PROFILE}
  Connector:  ${SCREEN_CONNECTOR}
  RTSP URL:   ${URL_HUMAN}
  Auth:       $([[ -n $RTSP_USER ]] && echo "user=${RTSP_USER}" || echo "none")
  mediamtx:   systemctl status mediamtx
  publisher:  systemctl --user status screen-to-rtsp
╰────────────────────────────────────────────────────╯
EOF
